# Copyright Advanced Micro Devices, Inc.
# 
# SPDX-License-Identifier: MIT

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    network_mode: host
    volumes:
      - open_webui_data:/app/backend/data

volumes:
  open_webui_data:
